// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilwxxglxiotiialmissy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsd3h4Z2x4aW90aWlhbG1pc3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3NDgzMTIsImV4cCI6MjA1MjMyNDMxMn0.QQlW4J_uKVA2gAmJoAlMpHRh7gtAIy38iblWAzsR30g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);